apiVersion: v1
kind: Pod
metadata:
  generateName: ray-head-
  labels:
    component: ray-head
spec:
  containers:
  - name: ray-head
    image: rayproject/ray:latest
    command: ["/bin/bash", "-c", "--"]
    args: ["ray start --head --port=6379 --redis-password='5241590000000000'"]
    ports:
    - containerPort: 6379
    - containerPort: 8265